apiVersion: v1
kind: Pod
metadata: 
    name: gd-eks-runtime-tester
spec:
  containers: 
    - name: gd-eks-runtime-tester
      imagePullPolicy: Always
      image: aws_account_id.dkr.ecr.region.amazonaws.com/gd-eks-tester:latest
      args: ["sleep","infinity"]
